name: flutter_class_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
